ci:
  name: CI - Lint and Checks
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.6

    - name: Terraform Format Check
      run: |
        cd terraform
        terraform fmt -check -recursive

    - name: Terraform Validate
      run: |
        cd terraform
        terraform validate

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDS }}

    # Lint code with Flake8 (Python)
    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install

    - name: Python Lint
      run: poetry run flake8 .
