name: ETL CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: CI - Lint, Terraform Check, and Plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
          terraform_wrapper: false

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Terraform Format Check
        run: |
          cd terraform
          terraform fmt -check -recursive

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -input=false

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install

      - name: Python Lint
        run: poetry run flake8 .

  cd:
    name: CD - Deploy Infra and DAGs
    needs: ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
          terraform_wrapper: false

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve

      - name: Get Composer Bucket Name
        run: |
          cd terraform
          COMPOSER_BUCKET=$(terraform output -raw composer_bucket_name 2>/dev/null || echo "")
          echo "COMPOSER_BUCKET=$COMPOSER_BUCKET" >> $GITHUB_ENV

      - name: Verify Bucket Name
        run: |
          if [ -z "$COMPOSER_BUCKET" ]; then
            echo "❌ Error: Composer bucket name is empty"
            exit 1
          fi
          echo "✅ Verified Composer bucket: $COMPOSER_BUCKET"

      - name: Deploy DAGs to Composer
        run: |
          gcloud storage cp --recursive dags gs://$COMPOSER_BUCKET/dags/

      - name: Deploy Plugins to Composer
        run: |
          gcloud storage cp --recursive plugins gs://$COMPOSER_BUCKET/plugins/

      - name: Deploy Data to Composer
        run: |
          gcloud storage cp --recursive data gs://$COMPOSER_BUCKET/data/
