name: Debug Terraform Output

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Debug Outputs
        run: |
          cd terraform
          echo "=== RAW OUTPUT ATTEMPT ==="
          terraform output -raw composer_bucket_name || echo "RAW OUTPUT FAILED"
          
          echo "=== JSON OUTPUT ==="
          terraform output -json
          
          echo "=== STATE LIST ==="
          terraform state list
          
          echo "=== BUCKET RESOURCE DETAILS ==="
          terraform state show $(terraform state list | grep google_storage_bucket) || echo "NO BUCKET FOUND"